[package]
name = "roadsim-domain"
description = "Backend-independent RoadSim Design Model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
roadsim-types = { version = "0.1.0", path = "../roadsim-types" }
serde.workspace = true

[dev-dependencies]
proptest.workspace = true
serde_json.workspace = true

[lints]
workspace = true
